-- Insert default roles
INSERT INTO roles(name) VALUES('ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_CUSTOMER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_EMPLOYEE') ON CONFLICT DO NOTHING;
