apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-service.fullname" . }}-secret
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
type: Opaque
data:
  database-username: {{ .Values.database.username | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
  jwt-secret: {{ .Values.jwt.secret | b64enc }}
